# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba6ea9f8036e7af9a715d44db7825ad689532a7876162a4c09c4fd28f181a9d4878b39ac7845924638063faad1750a183270f29ee18448e2a9df5bce266f5a4

test:
  secret_key_base: 4e631a931af2cbd2950dd3e7bf31bf96dabf4b86b1cdf40648e7c2fa9a954a657895cbe042be9e8b63ab3d270600ed85af2af0bd14fdb40f3d04fb36ddd6226d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
